allprojects {
    ext.kotlin_version = '2.0.10'
    repositories {
        google()
        mavenCentral()
    }
    buildscript {
        
   dependencies {
    // ... other dependencies
       classpath 'com.google.gms:google-services:4.3.14'


   // classpath 'com.google.gms:google-services:4.4.2'
   //  with youtube id("com.google.gms:google-services") version "4.4.2" apply false

       
  }
}
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
